# Generated by Django 4.1.2 on 2022-11-16 19:39

import ads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='name',
            field=models.CharField(max_length=255, validators=[ads.models.name_length_validators]),
        ),
    ]
