# Generated by Django 4.1.2 on 2022-11-16 20:02

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(null=True, validators=[user.models.age_validators]),
        ),
    ]
